import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from config import FRONTEND_ORIGIN
from models import FallbackCard
from orchestrator import handle_query

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=[FRONTEND_ORIGIN],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class HistoryEntry(BaseModel):
    role: str
    content: str


class QueryRequest(BaseModel):
    query: str
    history: list[HistoryEntry] = []


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    # Starlette's default 500 for an uncaught exception is generated by
    # ServerErrorMiddleware, which sits outside CORSMiddleware in the stack —
    # so without this handler the response has no CORS headers and shows up
    # in the browser as a CORS error instead of the underlying 500 (e.g. a
    # Gemini rate-limit error). A registered exception_handler is run by
    # ExceptionMiddleware instead, which is inside CORSMiddleware.
    logger.exception("Unhandled error in %s", request.url.path)
    return JSONResponse(
        status_code=500,
        content={
            "cards": [
                FallbackCard(
                    message="An unexpected error occurred. Please try again or contact Guest Services."
                ).model_dump()
            ],
            "connector_label": None,
        },
    )


@app.post("/query")
def query(request: QueryRequest):
    return handle_query(request.query, request.history)
